language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo add-apt-repository ppa:beineri/opt-qt542 -y
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8
       && export CXX="g++-4.8" ; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4
       && export CXX="clang++-3.4"; fi

  - sudo apt-get install -qq qt54base

before_script:
  - source /opt/qt54/bin/qt54-env.sh

  - if [ "$CXX" = "clang++-3.4" ]; then export QMAKESPEC=linux-clang; fi

script:
  - qmake
  - make -j2 -k

notifications:
  email: false
