language: cpp

compiler:
  - clang
  - gcc

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; export QMAKESPEC=linux-g++; fi
  - if [ "$CXX" == "clang++" ]; export QMAKESPEC=linux-g++; fi

  - sudo apt-get install -qq qt55base

before_script:
  - source /opt/qt55/bin/qt55-env.sh

script:
  - qmake
  - make -j2 -k

notifications:
  email: false
