version: 1.0.{branch}.{build}
os: Visual Studio 2013
clone_folder: c:\projects\openhomm
init:
- cmd: >-
    set PATH=C:\Qt\5.5\msvc2013_64\bin;%PATH%

    call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
environment:
  QMAKESPEC: win32-msvc2013
install:
- cmd: >-
    cd C:\projects\openhomm

    git submodule update --init --recursive
build_script:
- cmd: >-
    cd C:\projects\openhomm

    qmake -r

    nmake release
test: off
deploy: off
